# Generated by Django 3.1.5 on 2021-01-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ImageLink',
            field=models.FileField(upload_to=''),
        ),
    ]
