# Generated by Django 3.1.5 on 2021-01-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_auto_20210107_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Mode_of_payment',
            field=models.PositiveSmallIntegerField(choices=[('cash', 'Cash_OnDelivery'), ('paytm', 'Paytm_bank'), ('card', 'card')], default=1),
        ),
    ]
