# Generated by Django 3.1.5 on 2021-01-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_auto_20210111_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Mode_of_payment',
            field=models.PositiveSmallIntegerField(choices=[('cash', 'Cash_OnDelivery'), ('paytm', 'Paytm_bank'), ('card', 'card_type')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.PositiveSmallIntegerField(choices=[('new', 'New_status'), ('paid', 'Paid_status')], default=1),
        ),
    ]
