# Generated by Django 3.1.5 on 2021-01-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0004_auto_20210111_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Mode_of_payment',
            field=models.CharField(choices=[('cash', 'Cash_OnDelivery'), ('paytm', 'Paytm_bank'), ('card', 'card_type')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('new', 'New_status'), ('paid', 'Paid_status')], max_length=30),
        ),
    ]
